name: taxpal
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dash_chat_2: ^0.0.21
  http: ^1.4.0
  flutter_tts: ^4.2.3
  speech_to_text: ^7.2.0
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  media_gallery_saver: ^1.1.0
  image_gallery_saver: ^2.0.3
  unicons: ^3.0.0
  shared_preferences: ^2.5.3


  intl: any
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  pluto_grid: ^8.0.0
  excel: ^4.0.6
  google_sign_in: ^6.2.2
  get: ^4.7.2
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:


  uses-material-design: true
