// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABmw1CKfjRA_A0nZc6CbCAeahD091OFGg',
    appId: '1:425676843416:web:d31c58f4feac1ba6f4e3ed',
    messagingSenderId: '425676843416',
    projectId: 'taxpal-5608a',
    authDomain: 'taxpal-5608a.firebaseapp.com',
    storageBucket: 'taxpal-5608a.firebasestorage.app',
    measurementId: 'G-4HRFPJV1BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpUS_qWbC0KZdL9Vtr2HHLkgrfB79vg5k',
    appId: '1:425676843416:android:1e548e9e224d2b2af4e3ed',
    messagingSenderId: '425676843416',
    projectId: 'taxpal-5608a',
    storageBucket: 'taxpal-5608a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJdEBjnKj6f5tgEzv4XesWTW3bYr41dPU',
    appId: '1:425676843416:ios:9b842275b1fb86a2f4e3ed',
    messagingSenderId: '425676843416',
    projectId: 'taxpal-5608a',
    storageBucket: 'taxpal-5608a.firebasestorage.app',
    iosBundleId: 'com.nubiarabo.taxpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJdEBjnKj6f5tgEzv4XesWTW3bYr41dPU',
    appId: '1:425676843416:ios:9b842275b1fb86a2f4e3ed',
    messagingSenderId: '425676843416',
    projectId: 'taxpal-5608a',
    storageBucket: 'taxpal-5608a.firebasestorage.app',
    iosBundleId: 'com.nubiarabo.taxpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABmw1CKfjRA_A0nZc6CbCAeahD091OFGg',
    appId: '1:425676843416:web:351d02840e1e74daf4e3ed',
    messagingSenderId: '425676843416',
    projectId: 'taxpal-5608a',
    authDomain: 'taxpal-5608a.firebaseapp.com',
    storageBucket: 'taxpal-5608a.firebasestorage.app',
    measurementId: 'G-PZKJEEDW8Y',
  );
}
